spring:
  datasource:
    url: jdbc:mysql://localhost:3306/waffleuniv
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show-sql: true
        format-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: 64461f01e1af406da538b9c48d801ce59142452199ff112fb5404c8e7e98e3ff
  redis:
    host: localhost
    port: 6379

google:
  client-id: "281963831825-53kidtc5diijt9hqatvjng51jocdb7hm.apps.googleusercontent.com"
  client-secret: "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"
  redirect-uri: "http://localhost:8080/auth/google/callback"

springdoc:
  api-docs:
    path: /custom-api-docs
    groups:
      enabled: true
  swagger-ui:
    path: /swagger-ui-custom.html
    enabled: true
    groups-order: ASC
    tags-sorter: alpha
    operations-sorter: alpha
    display-request-duration: true
    doc-expansion: none
    cache:
      disabled: true
    model-and-view-allowed: true
